name: Ping Render Site

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Site
        run: curl -s ${{ https://teladoc.onrender.com/home }}
